[Rainmeter]
Update=-1
AccurateText=1
OnRefreshAction=[!Move "(#SCREENAREAWIDTH# / 2) - (950 / 2)" "100"]

[Variables]
@IncludeConfig=#CURRENTPATH#Config\MainConfig.inc

NumberOfDividers=[#AutoDividerCalc[#NumberOfItems]]

;----------------------------------------------------
; # # BEGIN EDITING BELOW # # # # # # # # # # # # # #
;----------------------------------------------------
; value which intended to change by user
TaskFile=#CURRENTPATH#Instructions.txt
;TaskFile="#SKINSPATH#Droptop Community Apps\Apps\YouTube_Checker-TheyCallMePapa\Instructions\Instructions.txt"

DropdownMenuWidth=950

NumberOfItems=1

DividerExists1=0
DividerExists2=0
DividerExists3=0
DividerExists4=0
DividerExists5=0
DividerExists6=0
DividerExists7=0
DividerExists8=0
DividerExists9=0

CheckmarkKeyA=CustomCheckmark1
CheckmarkKeyB=CustomCheckmark2
CheckmarkKeyC=CustomCheckmark3

;----------------------------------------------------

NumberOfBoxes=1

BoxHeight1=225

;----------------------------------------------------

ItemIsFolder1=0
ItemIsToggle1=0
ItemIsCheckmark1=0
ItemCheckmarkGroup1=
ItemCheckmarkValue1=
ItemToggleKey1=
ItemIconFileName1=blank
ItemText1=YOUTUBE CHECKER INSTRUCTIONS FOR USE
ItemAction1=

ItemIsFolder2=1
ItemIsToggle2=0
ItemIsCheckmark2=0
ItemCheckmarkGroup2=
ItemCheckmarkValue2=
ItemToggleKey2=
ItemIconFileName2=blank
ItemText2=Box2 Feed Info
ItemAction2=

ItemIsFolder3=1
ItemIsToggle3=0
ItemIsCheckmark3=0
ItemCheckmarkGroup3=
ItemCheckmarkValue3=
ItemToggleKey3=
ItemIconFileName3=blank
ItemText3=Box3 Feed Info
ItemAction3=

ItemIsFolder4=1
ItemIsToggle4=0
ItemIsCheckmark4=0
ItemCheckmarkGroup4=
ItemCheckmarkValue4=
ItemIconFileName4=blank
ItemToggleKey4=
ItemText4=Box4 Feed Info
ItemAction4=

ItemIsFolder5=1
ItemIsToggle5=0
ItemIsCheckmark5=0
ItemCheckmarkGroup5=
ItemCheckmarkValue5=
ItemToggleKey5=
ItemIconFileName5=blank
ItemText5=Box5 Feed Info
ItemAction5=

ItemIsFolder6=1
ItemIsToggle6=0
ItemIsCheckmark6=0
ItemCheckmarkGroup6=
ItemCheckmarkValue6=
ItemToggleKey6=
ItemIconFileName6=blank
ItemText6=Number of Feeds
ItemAction6=

ItemIsFolder7=0
ItemIsToggle7=0
ItemIsCheckmark7=1
ItemCheckmarkGroup7=A
ItemCheckmarkValue7=20
ItemToggleKey7=CustomCheckmark1
ItemIconFileName7=blank
ItemText7=Checkmark Group A
ItemAction7=

ItemIsFolder8=0
ItemIsToggle8=0
ItemIsCheckmark8=1
ItemCheckmarkGroup8=B
ItemCheckmarkValue8=5
ItemToggleKey8=CustomCheckmark2
ItemIconFileName8=blank
ItemText8=Checkmark Group B
ItemAction8=

ItemIsFolder9=0
ItemIsToggle9=0
ItemIsCheckmark9=1
ItemCheckmarkGroup9=B
ItemCheckmarkValue9=10
ItemToggleKey9=CustomCheckmark2
ItemIconFileName9=blank
ItemText9=Checkmark Group B
ItemAction9=

ItemIsFolder10=0
ItemIsToggle10=0
ItemIsCheckmark10=1
ItemCheckmarkGroup10=B
ItemCheckmarkValue10=15
ItemToggleKey10=CustomCheckmark2
ItemIconFileName10=blank
ItemText10=Checkmark Group B
ItemAction10=

;----------------------------------------------------
; Strings
;----------------------------------------------------

[1]
StringAlign=Center
X=(#DropdownMenuWidth# /2)
Y=10
MouseOverAction=[]
MouseLeaveAction=[]

[2]

[3]

[4]

[5]

[6]

[7]

[8]

[9]

[10]

;----------------------------------------------------
; Icons
;----------------------------------------------------

[1Icon]

[2Icon]

[3Icon]

[4Icon]

[5Icon]

[6Icon]

[7Icon]

[8Icon]

[9Icon]

[10Icon]

;----------------------------------------------------
; Arrows
;----------------------------------------------------

[1Arrow]

[2Arrow]

[3Arrow]

[4Arrow]

[5Arrow]

[6Arrow]

[7Arrow]

[8Arrow]

[9Arrow]

[10Arrow]


[Box1]
MouseOverAction=[]
MouseLeaveAction=[]

[Box1Text]
Meter=String
MeasureName=MeasureReadFile
Text=%1
FontWeight=400
ClipString=2
Padding=2,10,0,10
X=[1Icon:X]
AntiAlias=1

[MeasureReadFile]
Measure=Script
ScriptFile=#CURRENTPATH#code.lua
FilePath=#TaskFile#
